# Generated by Django 5.1.7 on 2025-04-08 07:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOMSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bom_file', models.FileField(upload_to='bom_sheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bom_sheets',
            },
        ),
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('project_name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_details',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('intern', 'Intern')], max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_category',
            },
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=255)),
                ('item_descr', models.TextField(blank=True, null=True)),
                ('product_no', models.IntegerField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('thickness', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('breadth', models.IntegerField(blank=True, null=True)),
                ('material_type', models.CharField(blank=True, choices=[('plate', 'PLATE'), ('section', 'SECTION')], max_length=255, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'item_master',
            },
        ),
        migrations.CreateModel(
            name='MachineMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=255)),
                ('machine_type', models.CharField(choices=[('Electrical Machine', 'Electrical'), ('Mechanical Machine', 'Mechanical'), ('Production Machine', 'Production')], max_length=50)),
                ('amc_type', models.CharField(choices=[('Comprehensive', 'Comprehensive'), ('Non-Comprehensive', 'Non Comprehensive'), ('Non-AMC', 'Non Amc')], max_length=20)),
                ('vendor', models.CharField(blank=True, help_text='Applicable only for AMC types', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'machine_master',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('process_type', models.CharField(blank=True, max_length=255, null=True)),
                ('step_descr', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'step',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('quantity_available_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_available_pc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='setup.inventorycategory')),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='setup.itemmaster')),
            ],
            options={
                'db_table': 'inventory_items',
            },
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('Job_order_no', models.CharField(blank=True, max_length=150, null=True)),
                ('project_name', models.CharField(blank=True, max_length=150, null=True)),
                ('type_of_tower', models.CharField(blank=True, max_length=150, null=True)),
                ('note', models.CharField(blank=True, max_length=150, null=True)),
                ('mark_no', models.CharField(blank=True, max_length=150, null=True)),
                ('section', models.CharField(blank=True, max_length=150, null=True)),
                ('length', models.CharField(blank=True, max_length=150, null=True)),
                ('width', models.CharField(blank=True, max_length=150, null=True)),
                ('unit', models.CharField(blank=True, max_length=150, null=True)),
                ('wt_and_pcs', models.CharField(blank=True, max_length=150, null=True)),
                ('total_quantity', models.CharField(blank=True, max_length=150, null=True)),
                ('total_weight', models.CharField(blank=True, max_length=150, null=True)),
                ('operations', models.CharField(blank=True, max_length=150, null=True)),
                ('remarks', models.CharField(blank=True, max_length=150, null=True)),
                ('allocated_1', models.CharField(blank=True, max_length=150, null=True)),
                ('allocated_2', models.CharField(blank=True, max_length=150, null=True)),
                ('allocated_3', models.CharField(blank=True, max_length=150, null=True)),
                ('allocated_4', models.CharField(blank=True, max_length=150, null=True)),
                ('consumption_length', models.CharField(blank=True, max_length=150, null=True)),
                ('pieces', models.CharField(blank=True, max_length=150, null=True)),
                ('embossing', models.CharField(blank=True, max_length=150, null=True)),
                ('sin_no', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom_sheet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_cards', to='setup.bomsheet')),
                ('client_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_cards', to='setup.clientdetails')),
            ],
            options={
                'db_table': 'job_cards',
            },
        ),
        migrations.CreateModel(
            name='MachineMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(db_column='machine_id', on_delete=django.db.models.deletion.CASCADE, related_name='machine_material', to='setup.machinemaster')),
            ],
            options={
                'db_table': 'machine_material',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='setup.machinemaster')),
            ],
            options={
                'db_table': 'maintenance_record',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('consignment_id', models.CharField(max_length=100, unique=True)),
                ('workflow', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bom_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='setup.bomsheet')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='setup.clientdetails')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='setup.project')),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='StockDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_available_pc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('breadth', models.IntegerField(blank=True, null=True)),
                ('material_type', models.CharField(blank=True, max_length=255, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_details', to='setup.inventoryitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_details', to='setup.project')),
            ],
            options={
                'db_table': 'stockdetails',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciept_no', models.IntegerField(blank=True, null=True)),
                ('movement_type', models.CharField(choices=[('in', 'IN'), ('between', 'BETWEEN'), ('out', 'OUT')], max_length=20)),
                ('supplier', models.CharField(blank=True, null=True)),
                ('warehouse', models.CharField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('breadth', models.IntegerField(blank=True, null=True)),
                ('thickness', models.IntegerField(blank=True, null=True)),
                ('quantity_available_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_available_pc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movement_as_item', to='setup.itemmaster')),
                ('material_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movement_as_material_type', to='setup.itemmaster')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movement', to='setup.project')),
            ],
            options={
                'db_table': 'stock_movement',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_step_workflows', to='setup.step')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='setup.project')),
                ('steps', models.ManyToManyField(related_name='workflow_steps', to='setup.step')),
            ],
            options={
                'db_table': 'workflow',
            },
        ),
    ]
