# Generated by Django 5.1.7 on 2025-04-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='material_item',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='material_type',
            field=models.CharField(blank=True, choices=[('Plate', 'Plate'), ('Section', 'Section')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='material_type',
            field=models.CharField(blank=True, choices=[('Plate', 'Plate'), ('Section', 'Section')], max_length=255, null=True),
        ),
    ]
