# Generated by Django 5.1.7 on 2025-04-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_remove_stockmovement_material_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='item_id',
            new_name='item',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
