# Generated by Django 5.1.7 on 2025-04-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_rename_item_id_stockmovement_item_stockmovement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='material_type',
            field=models.CharField(blank=True, choices=[('Plate', 'plate'), ('Section', 'section')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='material_type',
            field=models.CharField(blank=True, choices=[('Plate', 'plate'), ('Section', 'section')], max_length=255, null=True),
        ),
    ]
