# Generated by Django 5.1.7 on 2025-04-09 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_alter_itemmaster_material_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='previous_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movement_from', to='setup.project'),
        ),
    ]
