# Generated by Django 5.1.7 on 2025-04-09 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_stockmovement_previous_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinematerial',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_material', to='setup.machinemaster'),
        ),
    ]
