# Generated by Django 5.1.7 on 2025-04-11 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_alter_machinematerial_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_used_pc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_inventories', to='setup.inventoryitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_inventories', to='setup.project')),
            ],
            options={
                'db_table': 'project_inventory',
                'unique_together': {('project', 'inventory_item')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='inventory_items',
            field=models.ManyToManyField(related_name='projects', through='setup.ProjectInventory', to='setup.inventoryitem'),
        ),
    ]
