# Generated by Django 5.1.7 on 2025-04-11 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_projectinventory_project_inventory_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='project',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='steps',
        ),
        migrations.AddField(
            model_name='workflow',
            name='step_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step1', to='setup.step'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='step_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step2', to='setup.step'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='step_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step3', to='setup.step'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='step_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step4', to='setup.step'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='step_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step5', to='setup.step'),
        ),
    ]
