# Generated by Django 5.1.7 on 2025-04-11 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_remove_workflow_current_step_remove_workflow_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='status',
        ),
    ]
