# Generated by Django 5.1.7 on 2025-04-11 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_remove_workflow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='setup.workflow'),
        ),
    ]
