# Generated by Django 5.1.7 on 2025-04-12 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='setup.employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='setup.machinemaster'),
        ),
    ]
