# Generated by Django 5.1.7 on 2025-05-02 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_project_employee_project_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr', to='setup.machinemaster')),
            ],
        ),
    ]
