# Generated by Django 5.1.7 on 2025-05-03 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0014_bomsheet_jc_produced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomsheet',
            name='jc_produced',
        ),
    ]
