# Generated by Django 5.1.7 on 2025-05-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0015_remove_bomsheet_jc_produced'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomsheet',
            name='jc_produced',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
