# Generated by Django 5.1.7 on 2025-05-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0016_bomsheet_jc_produced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomsheet',
            name='bom_file',
            field=models.FileField(upload_to='bom_sheet/'),
        ),
    ]
