# Generated by Django 5.1.7 on 2025-05-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0017_alter_bomsheet_bom_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='jc_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='release_date',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
