# Generated by Django 5.1.7 on 2025-05-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0018_jobcard_jc_no_jobcard_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='available_length',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='cutting_loss',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='serial_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
