# Generated by Django 5.1.7 on 2025-05-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0019_jobcard_available_length_jobcard_cutting_loss_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='allocated_2',
            new_name='consumed_length',
        ),
        migrations.RenameField(
            model_name='jobcard',
            old_name='allocated_3',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='jobcard',
            old_name='allocated_4',
            new_name='inventory_length',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='consumption_length',
        ),
    ]
