# Generated by Django 5.1.7 on 2025-05-15 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0020_rename_allocated_2_jobcard_consumed_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='client_details_id',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.project'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='tower_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='Job_order_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='allocated_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='available_length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='company_name',
            field=models.CharField(default='ERA T & D Ltd', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='consumed_length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='cutting_loss',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='embossing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='inventory_length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='jc_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='length',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='mark_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='note',
            field=models.TextField(default='Please fabricate the following Mark Nos. against with Mass Production.'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='operations',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='pieces',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='remarks',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='section',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='sin_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='total_quantity',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='total_weight',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='type_of_tower',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='unit',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='width',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='wt_and_pcs',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='jobcard',
            table=None,
        ),
        migrations.CreateModel(
            name='JobCardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning_weight', models.FloatField(blank=True, null=True)),
                ('raw_material_weight', models.FloatField(blank=True, null=True)),
                ('srn_weight', models.FloatField(blank=True, null=True)),
                ('wastage_percent', models.FloatField(blank=True, null=True)),
                ('wastage_weight', models.FloatField(blank=True, null=True)),
                ('calculated_weight', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='setup.jobcard')),
            ],
        ),
    ]
