# Generated by Django 5.1.7 on 2025-05-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0021_remove_jobcard_client_details_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='bom_sheet_id',
            new_name='bom_sheet',
        ),
    ]
