# Generated by Django 5.1.7 on 2025-05-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0023_employee_password_employee_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='pcs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='unit_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='weight_in_kgs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
