# Generated by Django 5.1.7 on 2025-05-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0024_jobcard_pcs_jobcard_unit_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomsheet',
            name='last_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
