# Generated by Django 5.1.7 on 2025-05-22 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0025_bomsheet_last_processed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='setup.clientdetails'),
        ),
    ]
