# Generated by Django 5.1.7 on 2025-06-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0027_tallydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallydata',
            name='tally_guid',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
