# Generated by Django 5.1.7 on 2025-07-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0030_sales_quantity_sales_rate_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cost',
            name='rate_unit',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
