# Generated by Django 5.1.7 on 2025-07-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0032_alter_employee_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
    ]
