# Generated by Django 4.2.7 on 2025-06-27 06:42

from django.db import migrations, models
import django.utils.timezone
import ledger.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TallyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', ledger.models.AutoDateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('tally_json_data', models.JSONField()),
                ('updated_at', ledger.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tally_data',
            },
        ),
    ]
