# Generated by Django 4.2.7 on 2025-06-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallydata',
            name='tally_guid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
