import React, { useEffect, useState } from "react";
import { Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Paper, Box, Button, Dialog, DialogTitle, DialogContent, TextField, DialogActions, IconButton, CardContent, Card, Typography } from "@mui/material";
import {  styled } from "@mui/system";
import EditIcon from "@mui/icons-material/Edit";
import DeleteIcon from "@mui/icons-material/Delete";
import endpoints from "../../utils/apiEndPoints";
import { apiRequest } from "../../utils/apiclient";
// import VisibilityIcon from "@mui/icons-material/Visibility";
// import { useNavigate } from "react-router-dom";

// const StyledTableContainer = styled(TableContainer)({
//   maxWidth: "90%",
//   margin: "20px auto",
//   boxShadow: "0px 4px 10px rgba(0, 0, 0, 0.1)",
//   borderRadius: "10px",
//   overflow: "hidden",
// });

// const StyledTableHead = styled(TableHead)({
//   backgroundColor: "#3f51b5",
//   "& th": {
//     color: "white",
//     fontWeight: "bold",
//   },
// });

const StyledTableRow = styled(TableRow)({
  "&:nth-of-type(even)": {
    backgroundColor: "#E7EBF0",
  },
});

interface Client {
  id: number;
  client_name: string;
  email: string;
  phone_number: string;
  address: string;
  project_name: string;
  start_date: string;
  end_date: string;
  created_at: string;
  updated_at: string;
  [key: string]: string | number; // ✅ Allow indexing
}


//   const inventoryItems: InventoryItem[] = [
//     {
//       category: "Electronics",
//       item_name: "Laptop",
//       item_code: "ITM001",
//       description: "High-performance laptop",
//       unit_of_measure: "pcs",
//       quantity_available: 10,
//       min_stock_level: 2,
//       max_stock_level: 20,
//       reorder_level: 5,
//       supplier: "Tech Supplies Inc.",
//       purchase_price: 1200.5,
//       last_updated: "2024-03-11",
//     },
//   ];
  
  

const ClientTable: React.FC = () => {
    //  const [openAddDialog, setOpenAddDialog] = useState(false);
    //  const [openEditDialog, setOpenEditDialog] = useState(false);
    //  const [editData, setEditData] = useState<Client | null>(null);
    //  const [openDeleteDialog, setOpenDeleteDialog] = useState(false);
    //  const [itemToDelete, setItemToDelete] = useState<Client | null>(null);

    //  const [clientData, setClientData] = useState<Client[]>([]);
     const [clients, setClients] = useState<Client[]>([]);
     const [openAddDialog, setOpenAddDialog] = useState(false);
     const [openEditDialog, setOpenEditDialog] = useState(false);
      const [editData, setEditData] = useState<Client | null>(null);
      const [openDeleteDialog, setOpenDeleteDialog] = useState(false);
      const [selectedClient, setSelectedClient] = useState<Client | null>(null);

     const [formData, setFormData] = useState<Client>({
      id: 0, // This will be auto-generated by backend
      client_name: "",
      email: "",
      phone_number: "",
      address: "",
      project_name: "",
      start_date: "",
      end_date: "",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    });
    useEffect(() => {
      const fetchClients = async () => {
          try {
              const response = await apiRequest<{ success: boolean; data?: { Employee?: Client[] } }>(
                  "GET",
                  endpoints.getClientDetails
              );
  
              console.log("📥 API Response:", response);
  
              if (response.success && response.data?.Employee && Array.isArray(response.data.Employee)) {
                  setClients(response.data.Employee);
              } else {
                  console.error("❌ Unexpected response format:", response);
              }
          } catch (error) {
              console.error("🚨 Error fetching client details:", error);
          }
      };
  
      fetchClients();
  }, []);
  
    
      
    const handleDeleteClick = (client: Client) => {
      setSelectedClient(client);
      setOpenDeleteDialog(true);
    };
    

    const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
      const { name, value } = event.target;
      
      setFormData((prevData) => ({
        ...prevData,
        [name]: value,
      }));
    };

    // Handle adding a new client
    const handleAddClient = async () => {
      try {
        const response = await apiRequest<{ success: boolean; data?: { id: number } }>(
          "POST",
          endpoints.createClientDetails,
          formData
        );
    
        console.log("📤 API Response:", response);
    
        if (response.success && response.data?.id) {
          const newClient: Client = {
            ...formData,
            id: response.data.id, // ✅ Extract `id` from `data`
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
          };
    
          setClients((prevClients: Client[]) => [...prevClients, newClient]);
          setOpenAddDialog(false);
          resetForm();
        } else {
          console.error("❌ Unexpected response format:", response);
        }
      } catch (error) {
        console.error("🚨 Error adding client:", error);
      }
    };
    
  
  
    
    

    const handleEditClick = (client: Client) => {
      setEditData(client);
      setOpenEditDialog(true);
    };
    
    const handleUpdateClient = async () => {
      if (!editData) return;
      
      console.log("Updating client:", editData);
  
      try {
          const response = await apiRequest<{ success: boolean }>(
              "PUT",
              endpoints.updateClientDetails,
              { ...editData, client_id: editData.id } // Ensure correct structure
          );
  
          if (response.success) {
              setClients((prevClients) =>
                  prevClients.map((client) =>
                      client.id === editData.id ? { ...client, ...editData } : client
                  )
              );
  
              setOpenEditDialog(false); // ✅ Close the edit dialog
          } else {
              console.error("❌ Update failed:", response);
          }
      } catch (error) {
          console.error("🚨 Error updating client:", error);
      }
  };
  



  const handleConfirmDelete = async () => {
    if (!selectedClient) return;

    try {
        const response = await apiRequest<{ success: boolean }>(
            "DELETE",
            `${endpoints.deleteClientDetails}?client_id=${selectedClient.id}`
        );

        if (response.success) {
            setClients((prevClients) =>
                prevClients.filter((client) => client.id !== selectedClient.id)
            );
            setOpenDeleteDialog(false);
            setSelectedClient(null);
        } else {
            console.error("❌ Delete failed:", response);
        }
    } catch (error) {
        console.error("🚨 Error deleting client:", error);
    }
};

    
  // Reset form after submission
  const resetForm = () => {
    setFormData({
      id: 0,
      client_name: "",
      email: "",
      phone_number: "",
      address: "",
      project_name: "",
      start_date: "",
      end_date: "",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    });
  };


  
  

      // const handleChange = (e: React.ChangeEvent<{ name?: string; value: unknown }>) => {
      //   const { name, value } = e.target;
      //   if (name) {
      //     setFormData((prevFormData) => ({
      //       ...prevFormData,
      //       [name]: name === "category" ? Number(value) : value, // Ensure category is stored as a number
      //     }));
      //   }
      // };
      

  
  // const handleUpdateInventoryItem = () => {
  //   // Update logic here
  //   setOpenEditDialog(false);
  // };
//   const handleUpdateInventoryItem = () => {
//     if (!editData || !editData.id) {
//         console.error("❌ Missing inventory_id:", editData);
//         alert("Error: Inventory ID is missing.");
//         return;
//     }

//     const apiUrl = "http://43.204.203.153:8000/inventory-item/update-inventory-item-details/";
//     const requestData = { inventory_id: editData.id, ...editData };

//     console.log("🛠️ Updating inventory item with data:", requestData); // Debugging log

//     fetch(apiUrl, {
//         method: "PUT",
//         headers: { "Content-Type": "application/json" },
//         body: JSON.stringify(requestData),
//     })
//     .then((response) => response.json())
//     .then((data) => {
//         if (data.success) {
//             console.log("✅ Item updated successfully:", data);
//             setOpenEditDialog(false);
//             // Optionally refresh inventory items
//         } else {
//             console.error("❌ Update failed:", data);
//             alert(`Error: ${data.message || "Failed to update item."}`);
//         }
//     })
//     .catch((error) => console.error("❌ Error updating item:", error));
// };

  
//     const navigate = useNavigate();
//   const handleOpenVisible = (item: Client) => {
//     console.log("Navigating with Machine ID:", item.id);
//     navigate("/inventoryitemid", { state: { categoryId: item.id } });
//   };
  // const handleDeleteClick = (item: InventoryItem) => {
  //   setItemToDelete(item);
  //   setOpenDeleteDialog(true);
  // };
  
  
//   const handleConfirmDelete = () => {
//     if (!itemToDelete || !itemToDelete.id) {
//         console.error("❌ Missing inventory_id:", itemToDelete);
//         alert("Error: Inventory ID is missing. Please try again.");
//         return;
//     }

//     const apiUrl = `http://43.204.203.153:8000/inventory-item/delete-inventory-item-details/?inventory_id=${itemToDelete.id}`;
//     console.log("🛠️ Deleting item with URL:", apiUrl); // Debugging log

//     fetch(apiUrl, { method: "DELETE" })
//         .then((response) => response.json())
//         .then((data) => {
//             if (data.success) {
//                 console.log("✅ Item deleted successfully:", data);
//                 setOpenDeleteDialog(false);
//                 setItemToDelete(null);
//                 // Optionally refresh inventory items
//             } else {
//                 console.error("❌ Deletion failed:", data);
//                 alert(`Error: ${data.message || "Failed to delete item."}`);
//             }
//         })
//         .catch((error) => console.error("❌ Error deleting item:", error));
// };


      
//       const handleAddInventoryItem = () => {
//         fetch("http://43.204.203.153:8000/inventory-item/create-inventory-item/", {
//           method: "POST",
//           headers: { "Content-Type": "application/json" },
//           body: JSON.stringify(formData),
//         })
//           .then((response) => response.json())
//           .then((data) => {
//             if (data.success) {
//               setOpenAddDialog(false);
//               setFormData({
//                 id:0,
//                 category: 0,  // ✅ Set to number instead of ""
//                 item_name: "",
//                 item_code: "",
//                 description: "",
//                 unit_of_measure: "",
//                 quantity_available: 0,
//                 min_stock_level: 0,
//                 max_stock_level: 0,
//                 reorder_level: 0,
//                 supplier: "",
//                 purchase_price: 0,
//                 last_updated: new Date(),  // ✅ Ensure `last_updated` is included
//             });
            
//             }
//           })
//           .catch((error) => console.error("Error adding inventory item:", error));
//       };
      
      
  return (
            <Card sx={{ bgcolor: '#E7EBF0', borderRadius: 2, boxShadow: `
              4px 4px 20px 0px #6F8CB069,
              -6px -6px 20px 0px #FFFFFF,
              2px 2px 4px 0px #728EAB1A
              `, p: 2 }}>
                <CardContent>
    <Paper elevation={3} style={{
        
      margin: "20px auto",
      borderRadius: "10px",
      background: "#E7EBF0",
      // boxShadow:
        // "4px 4px 20px 0px #6F8CB069, -6px -6px 20px 0px #FFFFFF, 2px 2px 4px 0px #728EAB1A",
        backgroundColor: "#E7EBF0",
         padding:"20px 20px"
    }}>
      <Box display="flex" justifyContent="flex-end" p={2}>
    <Button
      variant="contained"
      color="primary"
      onClick={() => setOpenAddDialog(true)}
      sx={{
        minWidth: 120,
        bgcolor: "#E7EBF0",
        color:"black",
        border:"1px solid grey",
        boxShadow:
          "4px 4px 20px 0px #6F8CB069, -6px -6px 20px 0px #FFFFFF, 2px 2px 4px 0px #728EAB1A",
      }}
    >
      Add Employee
    </Button>
  </Box>
          {/* <Box display="flex" justifyContent="flex-end" p={2}>
              <Button variant="contained" color="primary" onClick={() => setOpenAddDialog(true)}>
                Add Inventory
              </Button>
            </Box> */}
   {/* Table to Display Clients */}
   <TableContainer 
   component={Paper}
     sx={{
       bgcolor: "#E7EBF0",
       p: 1,
       maxWidth: "100%",
       overflowX: "auto",
       whiteSpace: "nowrap",
       "&::-webkit-scrollbar": {
         height: "5px", // Adjusts the horizontal scrollbar height
       },
       "&::-webkit-scrollbar-thumb": {
         background: "#888",
         borderRadius: "10px",
       },
       "&::-webkit-scrollbar-thumb:hover": {
         background: "#555",
       },  
     }}>
        <Table>
          <TableHead>
            <TableRow>
              {/* <TableCell>ID</TableCell> */}
              <TableCell>Client Name</TableCell>
              <TableCell>Email</TableCell>
              <TableCell>Phone Number</TableCell>
              <TableCell>Project Name</TableCell>
              <TableCell>Start Date</TableCell>
              <TableCell>End Date</TableCell>
              <TableCell>Action</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {clients.map((client) => (
               <StyledTableRow key={client.id} >
              {/* <TableRow key={client.id}> */}
                {/* <TableCell>{client.id}</TableCell> */}
                <TableCell>{client.client_name}</TableCell>
                <TableCell>{client.email}</TableCell>
                <TableCell>{client.phone_number}</TableCell>
                <TableCell>{client.project_name}</TableCell>
                <TableCell>{client.start_date}</TableCell>
                <TableCell>{client.end_date}</TableCell>
                <TableCell style={{display:"flex"}}>
                            {/* Edit Button */}
                            <IconButton 
                                color="primary" 
                                onClick={() => { 
                                }}
                            >
                             <EditIcon style={{color:"grey"}} onClick={() => handleEditClick(client)}/>
                            </IconButton>

                            {/* Delete Button */}
                            <IconButton  color="secondary">
                            <DeleteIcon style={{color:"grey"}} onClick={() => handleDeleteClick(client)}/>
                            </IconButton>
                            </TableCell>

              {/* </TableRow> */}
              </StyledTableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>



     {/* Add Client Dialog */}
     <Dialog open={openAddDialog} onClose={() => setOpenAddDialog(false)} fullWidth maxWidth="sm">
        <DialogTitle>Add New Client</DialogTitle>
        <DialogContent>
          {Object.keys(formData).map((key) => {
            if (key === "id" || key === "created_at" || key === "updated_at") return null; // Skip non-editable fields

            return key === "start_date" || key === "end_date" ? (
              // Date fields
              <TextField
                key={key}
                label={key.replace(/_/g, " ").toUpperCase()}
                name={key}
                type="date"
                fullWidth
                margin="dense"
                onChange={handleChange}
                value={formData[key] || ""}
                InputLabelProps={{ shrink: true }}
              />
            ) : (
              // Default text fields
              <TextField
              key={key}
              label={key.replace(/_/g, " ").toUpperCase()}
              name={key}
              fullWidth
              margin="dense"
              onChange={handleChange}
              value={formData[key as keyof Client] || ""} // ✅ Fixed typing issue
            />
            );
          })}
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setOpenAddDialog(false)} color="secondary">
            Cancel
          </Button>
          <Button onClick={handleAddClient} color="primary">
            Add
          </Button>
        </DialogActions>
      </Dialog>


{/* update Inventory Dialog */}
<Dialog open={openEditDialog} onClose={() => setOpenEditDialog(false)} fullWidth maxWidth="sm">
  <DialogTitle>Edit Client Details</DialogTitle>
  <DialogContent>
    <Box sx={{ maxHeight: 400, overflowY: "auto" }}>
      {editData &&
        Object.keys(editData).map((key) => {
          if (key === "id" || key === "created_at" || key === "updated_at") return null; // Skip non-editable fields

          return key === "start_date" || key === "end_date" ? (
            // Date Fields
            <TextField
              key={key}
              label={key.replace(/_/g, " ").toUpperCase()}
              name={key}
              type="date"
              fullWidth
              margin="dense"
              onChange={(e) =>
                setEditData({ ...editData, [key]: e.target.value })
              }
              value={editData[key] || ""}
              InputLabelProps={{ shrink: true }}
            />
          ) : (
            // Default Text Fields
            <TextField
              key={key}
              label={key.replace(/_/g, " ").toUpperCase()}
              name={key}
              fullWidth
              margin="dense"
              onChange={(e) =>
                setEditData({ ...editData, [key]: e.target.value })
              }
              value={editData[key] || ""}
            />
          );
        })}
    </Box>
  </DialogContent>
  <DialogActions>
    <Button onClick={() => setOpenEditDialog(false)} color="secondary">
      Cancel
    </Button>
    <Button onClick={handleUpdateClient} color="primary">
      Update
    </Button>
  </DialogActions>
</Dialog>


{/* Delete Inventory Dialog */}
<Dialog open={openDeleteDialog} onClose={() => setOpenDeleteDialog(false)} fullWidth maxWidth="xs">
  <DialogTitle>Confirm Delete</DialogTitle>
  <DialogContent>
    <Typography>Are you sure you want to delete ?</Typography>
  </DialogContent>
  <DialogActions>
    <Button onClick={() => setOpenDeleteDialog(false)} color="secondary">Cancel</Button>
    <Button onClick={handleConfirmDelete} color="error">Delete</Button>
  </DialogActions>
</Dialog>

    </Paper>
    </CardContent>
    </Card>
  );
};

export default ClientTable;