# Generated by Django 5.1.7 on 2025-05-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_app', '0002_remove_fabricationproduction_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabplusgalvaproduction',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='fabplusgalvaproduction',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='galvanizingproduction',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='galvanizingproduction',
            name='unit',
        ),
        migrations.AddField(
            model_name='fabplusgalvaproduction',
            name='job_work_towers_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='fabplusgalvaproduction',
            name='job_work_towers_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='fabplusgalvaproduction',
            name='own_steel_towers_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='fabplusgalvaproduction',
            name='own_steel_towers_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='galvanizingproduction',
            name='quantity_job_work',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='galvanizingproduction',
            name='quantity_own_zinc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='galvanizingproduction',
            name='value_job_work',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='galvanizingproduction',
            name='value_own_zinc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
    ]
