# Generated by Django 5.1.7 on 2025-05-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_app', '0003_remove_fabplusgalvaproduction_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarproduction',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='solarproduction',
            name='unit',
        ),
        migrations.AddField(
            model_name='solarproduction',
            name='job_work_towers_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='solarproduction',
            name='job_work_towers_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='solarproduction',
            name='own_steel_towers_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='solarproduction',
            name='own_steel_towers_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
    ]
