# Generated by Django 5.1.7 on 2025-05-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_app', '0004_remove_solarproduction_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticalcostparameters',
            name='consumption_formula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criticalcostparameters',
            name='daily_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='criticalcostparameters',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criticalcostparameters',
            name='is_monthly_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='criticalcostparameters',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criticalcostparameters',
            name='monthly_cost_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='criticalcostparameters',
            name='monthly_units_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='criticalcostparameters',
            name='target_consumption_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='criticalcostparameters',
            name='units_consumed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='criticalcostparameters',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
