# Generated by Django 5.1.7 on 2025-05-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_app', '0006_user_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapgenerationmetrics',
            name='actual_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
    ]
